"""
Pixel3DMM ComfyUI Custom Nodes
Generated by MCP Multi-Agent System - Coding Agent

This package provides ComfyUI nodes for 3D face reconstruction using the Pixel3DMM method.
"""

from .pixel3dmm_loader import Pixel3DMMLoader
from .face_reconstructor import FaceReconstructor3D
from .flame_optimizer import FLAMEOptimizer
from .mesh_exporter import MeshExporter
from .uv_predictor import UVPredictor
from .normal_predictor import NormalPredictor

# Node class mappings for ComfyUI
NODE_CLASS_MAPPINGS = {
    "Pixel3DMMLoader": Pixel3DMMLoader,
    "FaceReconstructor3D": FaceReconstructor3D,
    "FLAMEOptimizer": FLAMEOptimizer,
    "MeshExporter": MeshExporter,
    "UVPredictor": UVPredictor,
    "NormalPredictor": NormalPredictor,
}

# Display names for ComfyUI interface
NODE_DISPLAY_NAME_MAPPINGS = {
    "Pixel3DMMLoader": "🔧 Pixel3DMM Model Loader",
    "FaceReconstructor3D": "🎭 3D Face Reconstructor",
    "FLAMEOptimizer": "🔥 FLAME Parameter Optimizer",
    "MeshExporter": "📦 3D Mesh Exporter",
    "UVPredictor": "🗺️ UV Coordinate Predictor",
    "NormalPredictor": "📐 Surface Normal Predictor",
}

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "Pixel3DMMLoader",
    "FaceReconstructor3D", 
    "FLAMEOptimizer",
    "MeshExporter",
    "UVPredictor",
    "NormalPredictor",
]
